# Generated by Django 4.0.2 on 2022-05-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0007_auto_20201129_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='training_images/')),
            ],
        ),
    ]
