# Generated by Django 4.0.2 on 2022-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0008_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Facial Pay', 'Facial Pay')], max_length=15),
        ),
    ]
